### ISSUE TITLE
Broken tcp connection at the sender side

### ISSUE THREAD

**Issue by FatmaUVA** [Unidata/FMTP#21]
Figure out a way to find which tcp connection is broken to remove it from the socket list, so that the sender will not wait for a VCMTP_RETX_END from this socket.

Why this is important?
For each product, the sender should receive  VCMTP_RETX_END from each receiver indicating that the receiver received all the blocks of the product. Once the sender received VCMTP_RETX_END from all receivers or the time is out for this product, the sender will remove this product from the product list and notify ldm.
If a tcp connection is broken, for each product the sender should wait for the timeout before removing this product from the product list.

**Comment by shawnsschen** [comment]
broken connection with be handled by LDM

**Comment by semmerson** [comment]
The LDM won't handle a broken TCP connection in the VCMTP layer between a sender and receiver. Because a TCP connection doesn't indicate if it's broken unless and until something is written to it, the sending VCMTP layer will either have to periodically test the connection by writing something to it or accept that it won't  receive VCMTP_RETX_END messages from VCMTP receivers.

**Comment by shawnsschen** [comment]
Well, I should make it more clear. A TCP alive heartbeat will be added later to test within the VCMTP layer. For VCMTP-LDM integration, a broken connection will cause an exception and LDM can decide based on it.

**Comment by semmerson** [comment]
Careful. An unhandled exception in the VCMTP thread handling a TCP connection will cause the eitire process to terminate. Also, I'm not sure the LDM would know what to do with an exception thrown by such a thread.

**Comment by shawnsschen** [comment]
I remember once we discussed that LDM would call Stop() if it sees an exception. But I'm not sure about what LDM would do. Will it terminate and start a new process?

**Comment by semmerson** [comment]
A sending LDM must be able to handle an exception thrown by
vcmtpSendv3::Start(), but broken TCP connection within the VCMTP layer must
be handled by the VCMTP layer because the LDM wouldn't know what to do.

Regards,
Steve Emmerson

**Comment by shawnsschen** [comment]
Now FMTP has TCP keepalive and offline receiver handling.
