### ISSUE TITLE
VCMTP exception handling

### ISSUE THREAD

**Issue by shawnsschen** [Unidata/FMTP#31]
Both sender side and receiver side have Init() and Start() functions which would throw exceptions as well. But I think exceptions thrown by them should be handled by the caller since at the point these exceptions are thrown, independent threads haven't been created yet, there's only one single thread. Thus the caller can simply re-run whatever it tries to do.

**Comment by semmerson** [comment]
Almost by definition, exceptions thrown by a method must be handled somewhere in the call-stack of the method. It is the method's responsibility, however, to limit -- as much as possible -- any side-effects of being called if an exception is thrown.
