### ISSUE TITLE
Add buffer + blocking in VCMTP to run over rate-limited VC through Linux tc

### ISSUE THREAD

**Issue by mv5guva** [Unidata/FMTP#32]
Through "accidental" experimentation (the best kind) where Shawn ran back-to-back files (of sizes following a bounded Pareto distribution) from a test application over VCMTPv3 to a tc-rate controlled NIC, we identified that there had to be some form of rate control at the VCMTP layer or there could be packet losses at the sending host. For example, if the tc-rate limit is 100Mbps, and the CPU running the VCMTPv3 code and application is a multi-GHz machine, the application process will quickly flood the UDP buffer and qdisc buffer whose size is set by the limit parameter causing overflows (losses).

So we determined that we need to implement the sending-host buffer described in the COMPSAC paper. This paper showed that most of the IDD feedtypes were bursty with inter-creation times (we called them inter-arrival times in the paper) that followed long-tailed distributions. To smooth out these bursts and offer the UDP socket VCMTP blocks at some smooth rate (which would be the rate set in tc), we proposed a sending-host buffer. For example, for CONDUIT, we recommended a rate of 36Mbps with a 248 MiB. For one-day's data, we said had this rate and buffer setting been used then no products would have been dropped. 

But Steve pointed out that even with this planning, we need to have some blocking mechanism. In other words, if the Ethernet layer gave feedback that its qdisc buffer was full rather than just dropping packets, the VCMTP layer could react and block. (The push-back to LDM7 would need to be considered especially given the continuous nature of IDD traffic). We were wondering whether the Ethernet layer gave such feedback, when I recalled the TCP's CWR state (see Tao-Li*Linux document in Our-Group-Papers). There must be some such feedback from the Ethernet layer, because TCP goes into CWR state and cuts its cwnd in half. Since UDP offers no such mechanism for blocking, we need to implement this in VCMTP.

Summary: Implement buffer and blocking in VCMTP.

**Comment by shawnsschen** [comment]
Since VCMTPv3 has a sync API (vcmtpSendv3::sendProduct()), it returns after the product is sent out. This implies the feasibility of a product-wide blocking mechanism. We can insert intervals of different length to lower the rate. And for each product, a buffer in VCMTPv3 can smooth the rate.
But our goal is to eliminate sending side loss by matching the ethernet sending rate with the application sending rate. Then the question is if the application buffer size is properly set, why is it still possible to see mismatch between ethernet sending rate and application sending rate?

**Comment by shawnsschen** [comment]
As discussed, we decided to use an easier way to avoid sending side loss. The application (testSend) will send products with intervals, and between the app and VCMTP, there is a buffer smoothing the traffic. Also, we will add rate control in the VCMTP layer and tc layer to double assure that.
